server:
  port: 9735

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ossfile?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: root
    password: wswbh
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #password:
    password: 123456
    # Redis数据库索引（默认为0）
    database: 15
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
        # 连接池中的最小空闲连接
        min-idle: 1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAIugLGMMRE80v9
    accessKeySecret: bLmjLAOpVXUKoPLCOQXbbY27Vh3VPX
    bucketName: tom-file
  imm:
    endpoint: cn-hangzhou
    accessKeyId: LTAIugLGMMRE80v9
    accessKeySecret: bLmjLAOpVXUKoPLCOQXbbY27Vh3VPX
    projectName: document
  sms:
    regionId: cn-hangzhou
    SignName: Tom
    TemplateCode: SMS_172887101
    accessKeyId: LTAIugLGMMRE80v9
    secret: bLmjLAOpVXUKoPLCOQXbbY27Vh3VPX

